# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=18
markup=none

[title]
command=xdotool getactivewindow getwindowclassname 2>/dev/null | sed 's/./\u&/' || echo ""
interval=1
align=left
separator=true
min_width=#####

[update]
label=
command=pacman -Qu | wc -l
interval=3600

[ram]
label= 
#command=free -h | grep Mem | awk '{print $3}'
command=~/.config/i3/scripts/mem.sh
interval=5
min_width=000MB

[disk]
label=
command=df -h | grep sda | awk '{print $4}'
interval=5
min_width=000GB

#[iface]
#instance=wlan0
#color=#00FF00
#interval=10
#separator=false

[cpu_usage]
label=
interval=10
min_width=000.00%
command=~/.config/i3/scripts/i3blocks/cpu_usage
#separator=false

[bandwidth]
interval=5
command=echo $(~/.config/i3/scripts/i3blocks/bandwidth)
min_width=000K 000K

[time]
label= 
command=echo "$(date '+%d/%m/%Y %H:%M') |"
interval=5

#[power]
#command=~/.config/i3/scripts/power
#interval=once
#min_width=CPU: 10
